{% set data = load_setup_py_data() %}
package:
  name: grandiorite
  version: {{ data.get('version') }}

source:
  git_rev: v1.0.2
  git_url: https://github.com/tiegz/grandiorite.git

requirements:
  build:
    - python
    - setuptools
    - termcolor

  run:
    - python
    - setuptools
    - termcolor

test:
  imports:
    -

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}
  license_family: MIT
  license_file: LICENSE
  summary: {{ data.get('description') }}
